line-length = 100
target-version = "py311"

[lint]
# Keep the essentials (pyflakes/pycodestyle + import order)
# select = ["E", "F", "I"]

# Let notebooks be pedagogical: imports can appear mid-cell
per-file-ignores = { "**/*.ipynb" = ["E402"] }
