name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install tooling
        run: |
          pip install --upgrade pip
          pip install pre-commit pytest
      - name: Pre-commit
        run: |
          pre-commit install
          pre-commit run --all-files
      - name: Unit tests
        run: |
          pip install -e ./grader
          pytest -q
  integration-lite:
    runs-on: ubuntu-latest
    needs: [lint-and-test]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate Lab 01 beacon PCAP
        run: |
          pip install --quiet --upgrade pip
          pip install --quiet scapy
          python scripts/make_beacon_pcap.py pcaps/input.pcap

      - name: Build & run lite stack (no UI)
        run: |
          docker compose -f compose/docker-compose.lite.yml up --build --no-color

      - name: Install grader & grade sample answers
        run: |
	        pip install -e ./grader
          labgrade labs/01_beacon labs/01_beacon/answers.sample.yml --logs ./logs

      - name: Assert logs exist and are non-empty
        run: |
          test -s logs/zeek/conn.log
          test -s logs/suricata/eve.json
