name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install tooling
        run: |
          pip install --upgrade pip
          pip install pre-commit pytest
      - name: Pre-commit
        run: |
          pre-commit install
          pre-commit run --all-files
      - name: Unit tests
        run: |
          pip install -e ./grader
          pytest -q

